import type { ChannelId, Genre, Lang } from "./types";

const ET = {
  skip: "Liigu sisu juurde",
  studio: "Studio",
  desk: "Pult",
  vocals: "Vokaal",
  visuals: "Pilt",
  matrix: "Maatriks",
  monitor: "Monitor",
  play: "Mängi",
  stop: "Peata",
  rec: "Salvesta",
  arm: "Käivita mootor",
  armed: "Mootor sees",
  bounce: "Bounce WAV",
  master: "Master",
  bpm: "BPM",
  swing: "Swing",
  drive: "Drive",
  glue: "Glue",
  ceiling: "Lagi",
  width: "Laius",
  center: "Keskne lukk",
  mute: "Mute",
  solo: "Solo",
  send: "Send",
  pan: "Pan",
  level: "Tase",
  kick: "Kick",
  bass: "Bass",
  hat: "Hats",
  perc: "Perc",
  lead: "Lead",
  vocal: "Vokaal",
  genre: "Žanr",
  hardstyle: "Hardstyle",
  rawstyle: "Rawstyle",
  techno: "Hard Techno",
  rap: "Rap",
  trap: "Trap",
  loadVocal: "Laadi vokaal",
  loadBeat: "Laadi biit",
  liveMic: "Mikrofon",
  recVoice: "Salvesta hääl",
  quantize: "Kvanti",
  restore: "Taasta",
  harmony: "Harmoonia",
  choir: "Koor",
  adlib: "Ad-lib",
  generate: "Genereeri",
  hook: "Hook",
  lyrics: "Sõnad",
  detectLyrics: "Tuvasta sõnad",
  fx: "FX ahel",
  dry: "Kuiv",
  hardDelay: "Hard delay",
  clubVerb: "Klubi reverb",
  radio: "Raadio fade",
  trapSpace: "Trap space",
  voiceBank: "Häälepank",
  leadVoice: "Lead",
  female: "Harmoonia",
  langVocal: "Keele foneetika",
  micTitle: "Mikrofoni profiil",
  micNone: "Mikrofoni pole veel profiilitud.",
  restoreOn: "Hardware-aware taastus",
  karestik: "Kärestik",
  mirror: "Peegeldus",
  buffer: "Puhver",
  latency: "Latentsus",
  velocity: "Kiirus V",
  signal: "Signaal S",
  need: "Aeg T",
  host: "Host",
  standalone: "Iseseisev",
  fl: "FL Studio",
  ableton: "Ableton Live",
  logic: "Logic Pro",
  translate: "Tõlge",
  phone: "Telefon",
  jbl: "JBL",
  festival: "Festival",
  localBridge: "Kohalik arvutus",
  localBridgeNote: "Web Audio + lõuend kasutab selle seadme GPU/CPU. ASIO4ALL jääb lauaarvuti kaaslaseks.",
  visualStyle: "Stiil",
  auto: "Auto",
  rings: "Rõngad",
  tunnel: "Tunnel",
  scope: "Ostsilloskoop",
  bars: "Tulp",
  prompt: "Visuaali juhis",
  promptHint: "50–70 sõna. Rütm tuleb helilt; sina suunad valguse, ruumi, materjali.",
  still: "Genereeri kaader",
  recordVis: "Salvesta pilt",
  radar: "Stuudio radar",
  radarGo: "Skaala Steelile",
  keys: "Z–M live lead · tühik mängi",
  emptyVocal: "Tühi pesa",
  recStart: "Salvestan… vajuta uuesti",
  recDone: "Hääl salvestatud",
  decodeFail: "Faili ei õnnestunud avada.",
  needArm: "Käivita mootor esimese puudutusega.",
  processing: "Töötlen",
  kernel: "Tuum",
  crew: "Meeskond",
  audit: "Audit",
  crewKicker: "STEEL · meeskond",
  crewTitle: "Seitse vahti, üks signaal.",
  crewLead:
    "Nõrk masin lükkab töö veebi. Tugev masin hoiab tuuma. Igal vahil on püsikäsk; vahid tiksuvad kuni leht elab.",
  hostSignal: "Hosti signaal",
  pathKernel: "Tuum",
  pathWeb: "Veeb",
  pathHybrid: "Hübriid",
  standingOrder: "Püsikäsk",
  issueOrder: "Anna käsk",
  crewLog: "Vahtide logi",
  watchOn: "Vahid sees",
  watchOff: "Vahid pausil",
  lastTick: "Viimane",
  dutyIdle: "Ootel",
  dutyWork: "Töös",
  dutyBlocked: "Blokeeritud",
  dutyPaused: "Paus",
  coresLabel: "Tuuma",
  memoryLabel: "Mälu",
  connectionLabel: "Ühendus",
  policyLabel: "Poliitika",
  forcePath: "Sunni tee",
  autoPath: "Auto",
  kernelKicker: "STEEL · tuum",
  kernelLead: "Kohalik AudioWorklet kui signaal kannatab; muidu veebitee suurema puhvriga.",
  banks: "Pank",
  film: "Film",
  theory: "Teooria",
  banksKicker: "STEEL · pank",
  banksTitle: "Kuu konteinerit. Viis pluginat pärast valikut.",
  banksLead:
    "Mass püsib suletud kuni valid panga. Siis laeb EDGE-CUT, MUD-VOID, PRESENCE-IRON, SAT-PLATE, AIR-WELL. Kuus rec-rada, igaüks eraldi.",
  loadBank: "Ava konteiner",
  sealed: "Suletud",
  loaded: "Sees",
  recLane: "Rec rada",
  plugins: "Pluginad",
  melt: "Sula beatiga",
  tune: "Autotune",
  analogMirror: "Analog-peegel",
  filmKicker: "STEEL · film",
  filmTitle: "Tuhat bini. Huul lukus.",
  filmLead:
    "Lainevonked joonistuvad reaalajas. Viseme tuleb sõnast ja RMS-ist. Kaamera on sinu. Pakk tuleb zipina menüüst.",
  downloadPack: "Laadi FILM zip",
  downloadXlsx: "Laadi pangad xlsx",
  lips: "Huul",
  filmStyle: "Film",
  cam: "Kaamera",
  recordFilm: "Salvesta klipp",
  theoryKicker: "STEEL · teooria",
  theoryTitle: "Kümme lisa. Lukustatud read.",
  theoryLead: "Kleebi suund või lugu. Dirt/clear. Öörada: TAKT-LOCK, ENERGY-MATCH, STEREO-MX. Rhyme-lock ei kirjuta su seemet ümber.",
  pasteTrack: "Kleebi suund",
  dirtClear: "Dirt / clear",
  extras: "Kümme lisa",
  lockSeed: "Lukusta seeme",
  writeHook: "Hook",
  writeVerse: "Salm",
  fixBars: "Paranda takt",
  hostLookup: "Hosti geo",
  chain: "Kett",
  chainRun: "Käivita kett",
  chainLead: "Sama tick. Noole järjekord. Tingimus jätab käsu vahele, juhe läheb edasi.",
  bus: "Buss",
  busLead: "Nimetatud faktid. Mitte extra 11. URL on brief — ffmpeg ei puutu.",
  busLock: "Lukusta drop",
  busPdf: "Buss PDF",
  busDoc: "Buss Word",
  busPpt: "Buss slaidid",
  pyramid: "Püramiid",
  plusV: "V+",
  minusV: "V−",
  nullTier: "Null",
  footer: "STEEL STUDIO · tuum / veeb · pangad suletud kuni valikuni · V+ / V−",
  et: "ET",
  en: "EN",
  ru: "RU",
  es: "ES",
  de: "DE",
  nightLane: "Öörada",
  nightLead:
    "Lead jääb vaikseks. Stack on valjem. See ei ole sinu kloon — sellel masinal ei ole voice-printi. MP3 on stand-in back vox, et saaksid jälgida midagi, mis istub peal, kui sina jääd vaikseks.",
  standin: "Laadi stand-in",
  standinOn: "Stand-in sees",
  variant: "Kümme kätt",
  applyKind: "Rakenda variant",
  quietLead: "Vaikne lead",
  loudStack: "Valjem stack",
  capsTitle: "Kolmas põlvkond",
  capsLead:
    "Kümme kätt sinu vahemikus. Moodul jäljendab ainult kui sa ise rappid. Stand-in on sildid. Voice-printi ei kirjutata.",
  hearKind: "Puuduta kätt — kuulad oma take'il. Rakenda kirjutab pessa. Rhyme-lock ei kirjuta stereotüüpi.",
  rapFirst: "Rapi või räägi esmalt.",
  takeLive: "Take sees. Kümme kätt avatud.",
  tagsOnly: "Sildid. Jäljendus ootab su take'i.",
  measureTake: "Mõõda take",
  gen3: "GEN 3",
  mimicOn: "Jäljendus sees",
  mimicOff: "Jäljendus kinni",
  f0: "F0",
  range: "Vahemik",
};

const EN: Record<keyof typeof ET, string> = {
  skip: "Skip to content",
  studio: "Studio",
  desk: "Desk",
  vocals: "Vocals",
  visuals: "Visuals",
  matrix: "Matrix",
  monitor: "Monitor",
  play: "Play",
  stop: "Stop",
  rec: "Record",
  arm: "Arm engine",
  armed: "Engine live",
  bounce: "Bounce WAV",
  master: "Master",
  bpm: "BPM",
  swing: "Swing",
  drive: "Drive",
  glue: "Glue",
  ceiling: "Ceiling",
  width: "Width",
  center: "Center lock",
  mute: "Mute",
  solo: "Solo",
  send: "Send",
  pan: "Pan",
  level: "Level",
  kick: "Kick",
  bass: "Bass",
  hat: "Hats",
  perc: "Perc",
  lead: "Lead",
  vocal: "Vocal",
  genre: "Genre",
  hardstyle: "Hardstyle",
  rawstyle: "Rawstyle",
  techno: "Hard Techno",
  rap: "Rap",
  trap: "Trap",
  loadVocal: "Load vocal",
  loadBeat: "Load beat",
  liveMic: "Microphone",
  recVoice: "Record voice",
  quantize: "Quantize",
  restore: "Restore",
  harmony: "Harmony",
  choir: "Choir",
  adlib: "Ad-lib",
  generate: "Generate",
  hook: "Hook",
  lyrics: "Lyrics",
  detectLyrics: "Detect lyrics",
  fx: "FX chain",
  dry: "Dry",
  hardDelay: "Hard delay",
  clubVerb: "Club reverb",
  radio: "Radio fade",
  trapSpace: "Trap space",
  voiceBank: "Voice bank",
  leadVoice: "Lead",
  female: "Harmony",
  langVocal: "Phonetics",
  micTitle: "Mic profile",
  micNone: "No microphone profiled yet.",
  restoreOn: "Hardware-aware restore",
  karestik: "Kärestik",
  mirror: "Mirror",
  buffer: "Buffer",
  latency: "Latency",
  velocity: "Velocity V",
  signal: "Signal S",
  need: "Time T",
  host: "Host",
  standalone: "Standalone",
  fl: "FL Studio",
  ableton: "Ableton Live",
  logic: "Logic Pro",
  translate: "Translation",
  phone: "Phone",
  jbl: "JBL",
  festival: "Festival",
  localBridge: "Local compute",
  localBridgeNote: "Web Audio and canvas use this device. ASIO4ALL stays a desktop companion.",
  visualStyle: "Style",
  auto: "Auto",
  rings: "Rings",
  tunnel: "Tunnel",
  scope: "Scope",
  bars: "Bars",
  prompt: "Visual direction",
  promptHint: "50–70 words. Rhythm comes from the audio; you steer light, space, material.",
  still: "Generate still",
  recordVis: "Record picture",
  radar: "Studio radar",
  radarGo: "Scale for Steel",
  keys: "Z–M live lead · space play",
  emptyVocal: "Empty slot",
  recStart: "Recording… tap again to stop",
  recDone: "Voice captured",
  decodeFail: "Could not open that file.",
  needArm: "Arm the engine with the first tap.",
  processing: "Processing",
  kernel: "Kernel",
  crew: "Crew",
  audit: "Audit",
  crewKicker: "STEEL · crew",
  crewTitle: "Seven watches, one signal.",
  crewLead:
    "A weak host shifts load onto the web path. A strong host keeps the kernel. Each watch holds a standing order and ticks while the page lives.",
  hostSignal: "Host signal",
  pathKernel: "Kernel",
  pathWeb: "Web",
  pathHybrid: "Hybrid",
  standingOrder: "Standing order",
  issueOrder: "Issue order",
  crewLog: "Watch log",
  watchOn: "Watch on",
  watchOff: "Watch paused",
  lastTick: "Last",
  dutyIdle: "Idle",
  dutyWork: "Working",
  dutyBlocked: "Blocked",
  dutyPaused: "Paused",
  coresLabel: "Cores",
  memoryLabel: "Memory",
  connectionLabel: "Link",
  policyLabel: "Policy",
  forcePath: "Force path",
  autoPath: "Auto",
  kernelKicker: "STEEL · kernel",
  kernelLead: "Local AudioWorklet when the signal holds; otherwise the web path with a larger buffer.",
  banks: "Banks",
  film: "Film",
  theory: "Theory",
  banksKicker: "STEEL · banks",
  banksTitle: "Six containers. Five plugins after the pick.",
  banksLead:
    "Mass stays sealed until you pick a bank. Then EDGE-CUT, MUD-VOID, PRESENCE-IRON, SAT-PLATE, AIR-WELL load. Six rec lanes, each editable.",
  loadBank: "Open container",
  sealed: "Sealed",
  loaded: "Live",
  recLane: "Rec lane",
  plugins: "Plugins",
  melt: "Melt into beat",
  tune: "Autotune",
  analogMirror: "Analog mirror",
  filmKicker: "STEEL · film",
  filmTitle: "A thousand bins. Lip locked.",
  filmLead:
    "The wave draws live. Visemes come from the lyric and RMS. The camera is yours. The pack leaves as a zip from the menu.",
  downloadPack: "Download FILM zip",
  downloadXlsx: "Download banks xlsx",
  lips: "Lips",
  filmStyle: "Film",
  cam: "Camera",
  recordFilm: "Record clip",
  theoryKicker: "STEEL · theory",
  theoryTitle: "Ten extras. Locked bars.",
  theoryLead: "Paste a direction or a track. Dirt/clear. Night lane: TAKT-LOCK, ENERGY-MATCH, STEREO-MX. Rhyme-lock will not rewrite your seed.",
  pasteTrack: "Paste direction",
  dirtClear: "Dirt / clear",
  extras: "Ten extras",
  lockSeed: "Lock seed",
  writeHook: "Hook",
  writeVerse: "Verse",
  fixBars: "Fix takt",
  hostLookup: "Host geo",
  chain: "Chain",
  chainRun: "Run chain",
  chainLead: "Same tick. Arrow order. Conditional skips the command, not the wire.",
  bus: "Bus",
  busLead: "Named facts. Not extra 11. A URL is a brief — ffmpeg never touches it.",
  busLock: "Lock drop",
  busPdf: "Bus PDF",
  busDoc: "Bus Word",
  busPpt: "Bus slides",
  pyramid: "Pyramid",
  plusV: "V+",
  minusV: "V−",
  nullTier: "Null",
  footer: "STEEL STUDIO · kernel / web · banks sealed until pick · V+ / V−",
  et: "ET",
  en: "EN",
  ru: "RU",
  es: "ES",
  de: "DE",
  nightLane: "Night lane",
  nightLead:
    "You whisper the lead. Stack is louder. That is not a clone of you — there is no voice-print on this machine. The MP3 is a stand-in back vox so you can track against something that sits up while you stay quiet.",
  standin: "Load stand-in",
  standinOn: "Stand-in live",
  variant: "Ten kinds",
  applyKind: "Apply kind",
  quietLead: "Quiet lead",
  loudStack: "Loud stack",
  capsTitle: "Third generation",
  capsLead:
    "Ten kinds on your range. The module mimics only after you rap. The stand-in is tags. No voice-print is written.",
  hearKind: "Tap a kind to hear it on your take. Apply writes the slot. Rhyme-lock keeps diction — no stock reaction.",
  rapFirst: "Rap or speak first.",
  takeLive: "Take live. Ten kinds open.",
  tagsOnly: "Tags only. Mimic waits for your take.",
  measureTake: "Measure take",
  gen3: "GEN 3",
  mimicOn: "Mimic on",
  mimicOff: "Mimic off",
  f0: "F0",
  range: "Range",
};

export type CopyKey = keyof typeof ET;

export function t(lang: Lang, key: CopyKey): string {
  return (lang === "en" ? EN : ET)[key];
}

export function channelLabel(lang: Lang, id: ChannelId): string {
  return t(lang, id);
}

export function genreLabel(lang: Lang, id: Genre): string {
  return t(lang, id);
}
